extends Node3D

## The Carver, the demigod who carves the masks: a concept model, not placed in any level.
## The scene is generated by tools/import/build_carver.gd.
##
## A slow idle by code, on top of the built pose: the arms holding work turn their masks,
## the carving arms next to them scrape at them in short strokes, and the rest of the fan
## sways a little, each arm off the others' beat. His head bows and lifts slowly.

## Arms (by index) that carve: their elbows pump and wrists flick.
const CARVING := [4, 6, 9, 10]
## Arms that hold a mask and turn it.
const TURNING := [5, 7, 8, 11]

## How fast the whole idle runs (1 = as built).
@export var speed := 1.0

var _rest := {}
var _time := 0.0


func _ready() -> void:
	for node in find_children("Shoulder*", "Node3D") + find_children("Elbow*", "Node3D") + find_children("Wrist*", "Node3D"):
		_rest[node] = node.basis
	_rest[%Head] = %Head.basis


func _process(delta: float) -> void:
	_time += delta * speed
	for i in 16:
		var phase := _time * 0.7 + i * 1.7
		var shoulder: Node3D = get_node("%%Shoulder%d" % i)
		var elbow: Node3D = get_node("%%Elbow%d" % i)
		var wrist: Node3D = get_node("%%Wrist%d" % i)
		shoulder.basis = _rest[shoulder] * Basis(Vector3.BACK, 0.04 * sin(phase))
		if i in CARVING:
			# A stroke: quick pull, slow return.
			var stroke := pow(0.5 + 0.5 * sin(_time * 2.6 + i), 3.0)
			elbow.basis = _rest[elbow] * Basis(Vector3.UP, 0.35 * stroke)
			wrist.basis = _rest[wrist] * Basis(Vector3.BACK, 0.4 * stroke)
		elif i in TURNING:
			elbow.basis = _rest[elbow] * Basis(Vector3.UP, 0.08 * sin(phase * 0.5))
			wrist.basis = _rest[wrist] * Basis(Vector3.RIGHT, 0.5 * sin(_time * 0.6 + i))
		else:
			elbow.basis = _rest[elbow] * Basis(Vector3.UP, 0.06 * sin(phase * 1.3))
	%Head.basis = _rest[%Head] * Basis(Vector3.RIGHT, 0.05 * sin(_time * 0.4))
