class_name HumanBody
extends NpcBody

## The body every human character wears — villagers, bandits, and the player once they
## fall. It is the human model on a skeleton with a physical bone for each part, and it
## owns the two ways that body answers a hit:
##
## - flinch(): everything above the hips briefly turns physical, takes the hit's impulse
##   at the part that was struck, and the pose eases back to normal. The hips stay
##   animated, so the character rocks with the blow but keeps its feet.
## - go_limp(): death. Every bone turns physical for good and the body falls wherever the
##   killing blow and its own momentum throw it.
##
## Neither is decided here. Like any death behaviour in this project, the character's
## own script calls them from its Health signals; this only knows how to do them.
##
## The scene is generated by tools/import/build_human_body.gd. Tune the skeleton,
## shapes and joint limits there; what this script exports is tuned on the instance.
## The calls an NPC makes on its body are the ones NpcBody declares; went_limp is its.
## The worn mask took a blow to the head and has `durability` left.
signal mask_damaged(durability: int)
## The worn mask split and fell off in pieces; the face beneath is bare.
signal mask_broken

## Overrides the model's material, which is how one body tells a villager from a bandit.
@export var material: Material:
	set(value):
		material = value
		if is_node_ready():
			_apply_material()
## The mask worn over the face, which is how one faction tells itself from another in the
## dark. Its worn_scene is instanced onto the head bone, origin at `mask_offset` from the
## bone, facing forward (-Z). Changing it on a living body swaps the face, which is how
## the player's body keeps up with what is in their Mask slot. Setting the mask it already
## wears changes nothing, so the face keeps its cracks.
@export var mask: MaskData:
	set(value):
		if value == mask:
			return
		mask = value
		if is_node_ready() and not _limp:
			_put_on_mask()
## Where the mask sits relative to the head bone, which is at the base of the skull.
@export var mask_offset := Vector3(0.0, 0.13, -0.135)
## Chance that a mask comes off and tumbles away when the body goes limp, as an item that
## can be picked up. Otherwise it stays on the face and is found among the body's things
## when it is searched; taking it from there takes it off the face.
@export_range(0.0, 1.0) var mask_pop_chance := 0.7
## Impulse the mask leaves the face with, in newton-seconds, on top of the killing blow's
## direction.
@export var mask_pop_impulse := 0.6
## Seconds a mask that came off passes through the body it came off, to get clear of it.
@export var mask_clear_time := 0.5
## A hit this far or more above the base of the skull, along the head bone, is a hit on
## the head, and wears the mask down as well as hurting its wearer.
@export var head_hit_height := 0.0
## Heard and seen where the mask was as it breaks: a BreakBurst scene, like a crate's.
@export var mask_break_sound: SoundBank = preload("res://resources/audio/break_wood.tres")
@export var mask_break_effect: PackedScene = preload("res://scenes/vfx/break_burst.tscn")
## What a mask is once it has split: one Shattered Mask for every kind of face, past
## wearing and past repair. A mask that breaks drops it; a mask on a dead face may become it.
@export var shattered_mask: ItemData = preload("res://resources/items/shattered_mask.tres")
## An NPC's mask takes the brunt of every hit, not just one to the head, and on death is
## rolled for: shattered, or left its own kind but badly damaged. The player's own mask
## leaves this off — it wears from head hits only and comes off as it is.
@export var npc_mask_wear := false
## How many times the damage a head hit costs an NPC's mask, against one to the body.
@export var head_hit_mask_wear := 2.0
## Chance an NPC's mask is shattered when its wearer dies; otherwise it stays its own
## kind with only `damaged_mask_left` of its durability.
@export_range(0.0, 1.0) var mask_shatter_chance := 0.75
## The share of its durability a mask that survives its wearer's death keeps, picked
## between x and y.
@export var damaged_mask_left := Vector2(0.1, 0.25)
## Hits in a game land harder than physics says they should: every impulse a hit puts
## into the bones is multiplied by this.
@export var impulse_scale := 2.5
## Cap on that scaled impulse, in newton-seconds, so a hurled barrel knocks a body over
## rather than launching it across the map.
@export var max_impulse := 60.0
## How far a hit shoves the whole character, as a multiple of what its impulse would do
## to a body of this mass. Read through get_knockback() by whoever moves the character.
@export var knockback_scale := 3.0

## Whether something poses this body every frame, as an NPC's BodyAnimator does. Its
## physical bones then follow the animated pose instead of staying in the rest pose.
@export var animated := false:
	set(value):
		animated = value
		if is_node_ready() and not _limp and not physical_bones.is_simulating_physics():
			_settle_physical_bones()

@export_group("Flinch")
## The bone that stays animated while the rest of the body flinches, keeping the
## character standing on it.
@export var anchor_bone := &"Hips"
## How much of the physical pose shows at the height of a flinch, 0..1.
@export_range(0.0, 1.0) var flinch_influence := 0.9
## Seconds for the pose to ease back from a flinch to the character's own.
@export var flinch_recovery := 0.55
## Damping on the bones while flinching, so a blow is absorbed rather than flailed.
@export var flinch_linear_damp := 5.0
@export var flinch_angular_damp := 7.0
## Gravity on the flinching bones. Zero, because a standing torso is an upturned
## pendulum: with gravity it would start to fold over in the time a flinch lasts.
@export var flinch_gravity_scale := 0.0

@onready var skeleton: Skeleton3D = %Skeleton
@onready var mesh: MeshInstance3D = %Mesh
@onready var physical_bones: PhysicalBoneSimulator3D = %PhysicalBones

var _bones: Array[PhysicalBone3D] = []
## Half the length of each bone's collision shape along the bone, for finding the part
## nearest a hit.
var _half_lengths := {}
## Each bone's authored gravity and damping, put back when a flinch ends.
var _authored := {}
var _limp := false
var _flinch: Tween
## The face drawn on the head, built from `mask`.
var _face: Node3D
## Where a mask left on a dead face is listed in its wearer's inventory, so the face can
## come off once that entry is taken.
var _face_entry: InventoryEntry
var _face_inventory: Inventory
## Rolls an NPC mask's fate on death. Seed it to make the roll repeatable.
var mask_rng := RandomNumberGenerator.new()
## What the mask comes off a dead body as, and with how much left (-1: as authored).
var _dead_mask: ItemData
var _dead_durability := -1

## What the worn mask has left, on the scale of its MaskData.durability. Putting a mask on
## starts it at full; whoever keeps the mask's wear elsewhere — the player's Equipment —
## sets it straight after. The face shows a crack once half of it is gone.
var mask_durability := 0:
	set(value):
		mask_durability = value
		_show_wear()


func _ready() -> void:
	for child in physical_bones.get_children():
		var bone := child as PhysicalBone3D
		if bone == null:
			continue
		_bones.append(bone)
		_half_lengths[bone] = _half_length_of(bone)
		_authored[bone] = [bone.gravity_scale, bone.linear_damp, bone.angular_damp]
	# The parts of one body never collide with each other — shoulders and chest overlap
	# at rest and would push each other apart — nor with the capsule of the character
	# wearing them.
	for i in _bones.size():
		for j in range(i + 1, _bones.size()):
			_bones[i].add_collision_exception_with(_bones[j])
	var actor := get_actor() as CollisionObject3D
	if actor and actor != self:
		physical_bones.physical_bones_add_collision_exception(actor.get_rid())
	_settle_physical_bones()
	_apply_material()
	_put_on_mask()


func is_limp() -> bool:
	return _limp


## The middle of the body, wherever it has fallen: what a death camera looks at.
func get_center() -> Vector3:
	var middle := _find_bone(&"Spine")
	return middle.global_position if middle else global_position + Vector3.UP


## The vector from a bone's head to its far end — the knee to the sole, the elbow to the
## fingertips — in the body's rest frame. Read off the bone's physical body, which the
## builder centres halfway along it.
func get_bone_tail(bone_name: StringName) -> Vector3:
	var bone := _find_bone(bone_name)
	return bone.body_offset.origin * 2.0 if bone else Vector3.ZERO


## The impulse `info` puts into this body, scaled and capped.
func get_impulse(info: DamageInfo) -> Vector3:
	if info == null:
		return Vector3.ZERO
	return (info.get_impulse() * impulse_scale).limit_length(max_impulse)


## How `info` shoves the whole character: a velocity, flat along the ground, for the
## character's own movement to add and then shed.
func get_knockback(info: DamageInfo) -> Vector3:
	var impulse := get_impulse(info)
	impulse.y = 0.0
	return impulse * knockback_scale / maxf(get_total_mass(), 1.0)


func get_total_mass() -> float:
	var total := 0.0
	for bone in _bones:
		total += bone.mass
	return total


## Rocks the body with a hit that did not kill. A second hit while the first is still
## playing out adds its impulse to the motion already there.
func flinch(info: DamageInfo) -> void:
	if _limp or info == null:
		return
	var impulse := get_impulse(info)
	if impulse.is_zero_approx():
		return
	var flinching: Array[PhysicalBone3D] = []
	var names: Array[StringName] = []
	for bone in _bones:
		if bone.bone_name != String(anchor_bone):
			flinching.append(bone)
			names.append(StringName(bone.bone_name))
	if flinching.is_empty():
		return
	if not physical_bones.is_simulating_physics():
		for bone in flinching:
			bone.gravity_scale = flinch_gravity_scale
			bone.linear_damp = flinch_linear_damp
			bone.angular_damp = flinch_angular_damp
		physical_bones.influence = 0.0
		physical_bones.active = true
		physical_bones.physical_bones_start_simulation(names)
	_push(_nearest_bone(info.position, flinching), impulse, info.position)

	# Straight up to full strength, held a moment, then eased back. A hit landing
	# mid-recovery ramps up from wherever the pose is rather than snapping to it.
	if _flinch:
		_flinch.kill()
	_flinch = create_tween()
	_flinch.tween_property(physical_bones, "influence", flinch_influence, 0.05)
	_flinch.tween_property(physical_bones, "influence", 0.0, flinch_recovery).set_trans(
		Tween.TRANS_SINE
	).set_ease(Tween.EASE_IN_OUT)
	_flinch.tween_callback(_end_flinch)


## Lets the whole body fall, for good. `carried_velocity` is how the character was
## moving, so a body killed mid-run keeps going as it drops; the killing blow's impulse
## lands on top of that at the part it struck.
func go_limp(info: DamageInfo = null, carried_velocity := Vector3.ZERO) -> void:
	if _limp:
		return
	_limp = true
	if _flinch:
		_flinch.kill()
		_flinch = null
	for bone in _bones:
		_restore_authored(bone)
	physical_bones.active = true
	# Bones already flinching keep their motion; the rest start from the current pose.
	physical_bones.physical_bones_start_simulation()
	var blend := create_tween()
	blend.tween_property(physical_bones, "influence", 1.0, 0.08)
	for bone in _bones:
		bone.linear_velocity += carried_velocity
	if info:
		var impulse := get_impulse(info)
		_push(_nearest_bone(info.position, _bones), impulse, info.position)
	_dead_mask = mask
	_dead_durability = mask_durability
	if _face and npc_mask_wear and mask:
		_roll_mask_on_death()
	if _face:
		if randf() < mask_pop_chance or not _leave_mask_on():
			# Deferred: adding a body from inside a physics callback is not allowed.
			_knock_off_mask.call_deferred(_face, info, carried_velocity)
			_face = null
	went_limp.emit()


func _end_flinch() -> void:
	_flinch = null
	if _limp:
		return
	physical_bones.physical_bones_stop_simulation()
	_settle_physical_bones()
	for bone in _bones:
		_restore_authored(bone)


## Puts the simulator back to rest between hits. On a body that is not animated it sleeps
## and the bones stay where the rest pose put them. On an animated one it keeps running
## with no influence on the pose, which is what carries the bones along with the
## animation — so a hit lands on the limb where it is drawn, and a flinch or a fall starts
## from the pose the body was really in.
func _settle_physical_bones() -> void:
	physical_bones.influence = 0.0
	physical_bones.active = animated


func _restore_authored(bone: PhysicalBone3D) -> void:
	var authored: Array = _authored[bone]
	bone.gravity_scale = authored[0]
	bone.linear_damp = authored[1]
	bone.angular_damp = authored[2]


## Applies `impulse` to `bone` at `at`, or through its centre when the hit carried no
## position.
func _push(bone: PhysicalBone3D, impulse: Vector3, at: Vector3) -> void:
	if bone == null or impulse.is_zero_approx():
		return
	if at.is_zero_approx():
		bone.apply_central_impulse(impulse)
	else:
		# Clamped to the bone, so a point recorded at the surface of a capsule or at a
		# thrown rock's centre does not become a long lever arm.
		var offset := (at - bone.global_position).limit_length(_half_lengths[bone] + 0.1)
		bone.apply_impulse(impulse, offset)


## The bone among `candidates` whose segment passes closest to `point`, or the chest when
## the hit recorded no point.
func _nearest_bone(point: Vector3, candidates: Array[PhysicalBone3D]) -> PhysicalBone3D:
	if point.is_zero_approx():
		var chest := _find_bone(&"Chest")
		return chest if chest in candidates else candidates.front()
	var nearest: PhysicalBone3D = null
	var nearest_distance := INF
	for bone in candidates:
		var axis := bone.global_basis.y.normalized()
		var half: float = _half_lengths[bone]
		var along := clampf((point - bone.global_position).dot(axis), -half, half)
		var distance := point.distance_to(bone.global_position + axis * along)
		if distance < nearest_distance:
			nearest = bone
			nearest_distance = distance
	return nearest


func _find_bone(bone_name: StringName) -> PhysicalBone3D:
	for bone in _bones:
		if bone.bone_name == String(bone_name):
			return bone
	return null


func _half_length_of(bone: PhysicalBone3D) -> float:
	for child in bone.get_children():
		var shape := (child as CollisionShape3D).shape if child is CollisionShape3D else null
		if shape is CapsuleShape3D:
			var capsule := shape as CapsuleShape3D
			return maxf(capsule.height * 0.5 - capsule.radius, 0.0)
		if shape is BoxShape3D:
			return (shape as BoxShape3D).size.y * 0.5
	return 0.0


func _apply_material() -> void:
	if mesh:
		mesh.material_override = material


## Hangs the mask's face on the head bone, so it turns, flinches and falls with the head,
## in place of whatever face was there. It is added here rather than in the generated
## scene so that rebuilding the body keeps it.
func _put_on_mask() -> void:
	if _face:
		_face.queue_free()
		_face = null
	if mask == null or mask.worn_scene == null:
		return
	var attachment := skeleton.get_node_or_null("HeadAttachment") as BoneAttachment3D
	if attachment == null:
		attachment = BoneAttachment3D.new()
		attachment.name = "HeadAttachment"
		attachment.bone_name = "Head"
		skeleton.add_child(attachment)
	_face = mask.worn_scene.instantiate() as Node3D
	_face.position = mask_offset
	attachment.add_child(_face)
	mask_durability = mask.durability


## A spike stuck in this body hangs from the bone it went into, through a
## BoneAttachment3D, so it follows that limb as it is animated and, once the body falls,
## as it tumbles. `part` is that bone when a fallen or flinching limb was struck;
## otherwise (the standing capsule) the bone nearest `point`.
func stick_point(point: Vector3, part: Node) -> Node3D:
	var bone := part as PhysicalBone3D
	if bone == null or not bone in _bones:
		if _bones.is_empty():
			return null
		bone = _nearest_bone(point, _bones)
	var attachment_name: String = "Stuck" + bone.bone_name
	var attachment := skeleton.get_node_or_null(attachment_name) as BoneAttachment3D
	if attachment == null:
		attachment = BoneAttachment3D.new()
		attachment.name = attachment_name
		attachment.bone_name = bone.bone_name
		skeleton.add_child(attachment)
	return attachment


## Whether a hit landing at `point` is a hit on the head: at or above the base of the
## skull, wherever the head is posed. A hit that recorded no point is not.
func is_head_hit(point: Vector3) -> bool:
	var head := skeleton.find_bone("Head")
	if point.is_zero_approx() or head < 0:
		return false
	var frame := skeleton.global_transform * skeleton.get_bone_global_pose(head)
	return (frame.affine_inverse() * point).y >= head_hit_height


## A blow to the head lands on the mask too: it wears down by the damage dealt, cracks
## once half of it is gone, and breaks off the face when nothing is left. An NPC's mask
## (`npc_mask_wear`) wears from every hit, and faster from one to the head. Like flinch(),
## the character's own script calls this when its Health is damaged; a mask authored with
## no durability never breaks.
func hit_mask(info: DamageInfo) -> void:
	if _limp or _face == null or info == null or info.amount <= 0 or mask.durability <= 0:
		return
	var wear := info.amount
	if is_head_hit(info.position):
		if npc_mask_wear:
			wear = roundi(info.amount * head_hit_mask_wear)
	elif not npc_mask_wear:
		return
	# An NPC's killing blow leaves the mask to the roll as it falls (go_limp).
	var health := Health.find_in(get_actor())
	if npc_mask_wear and health and not health.is_alive():
		return
	mask_durability = maxi(mask_durability - wear, 0)
	mask_damaged.emit(mask_durability)
	if mask_durability == 0:
		_break_mask()


## The mask splits and falls from the face in pieces, leaving a Shattered Mask where it
## was. Seen
## from behind it — the player's own, in first person — it is only heard: the pieces
## would fill the view.
func _break_mask() -> void:
	var face := _face
	_face = null
	Sfx.play_at(mask_break_sound, face.global_position)
	var camera := get_viewport().get_camera_3d()
	var from_inside := camera != null and get_actor().is_ancestor_of(camera)
	if mask_break_effect and not from_inside:
		var burst := mask_break_effect.instantiate() as Node3D
		burst.top_level = true
		if burst is BreakBurst:
			# The pieces fall to the wearer's feet, not to the bottom of the face.
			(burst as BreakBurst).setup(face, global_position.y)
		else:
			burst.position = face.global_position
		var tree := get_tree()
		(tree.current_scene if tree.current_scene else tree.root).add_child(burst)
	_drop_shattered.call_deferred(face.global_transform)
	face.queue_free()
	mask = null
	mask_broken.emit()


## What is left of a mask that split: a Shattered Mask, dropped where the face was.
## Deferred by the caller: adding a body from inside a physics callback is not allowed.
func _drop_shattered(at: Transform3D) -> void:
	var level := get_actor().get_parent()
	var loose := shattered_mask.spawn() as RigidBody3D if shattered_mask else null
	if level == null or loose == null:
		return
	level.add_child(loose)
	loose.global_transform = at
	keep_clear_of(loose, get_actor(), mask_clear_time)


## An NPC's mask, as its wearer goes limp: shattered (`mask_shatter_chance`), or still its
## own kind with little left. The face shows a full crack either way; whatever it now is
## comes off or stays on as before.
func _roll_mask_on_death() -> void:
	var fate := MaskWear.roll_on_death(mask_rng, mask, mask_durability, mask_shatter_chance,
			damaged_mask_left, shattered_mask)
	_dead_mask = fate[0]
	_dead_durability = fate[1]
	mask_durability = 0 if _dead_durability < 0 else _dead_durability


## Draws the worn mask's wear on its face: nothing above half, then a crack running
## further down it the less is left.
func _show_wear() -> void:
	if _face == null or mask == null or mask.durability <= 0:
		return
	MaskWear.show_crack(_face, float(mask_durability) / mask.durability)


## The mask comes away from a falling body as the item it is — the same object as one
## dropped out of an inventory — carried off by the blow and the body's own momentum. It
## lies where it lands until someone picks it up.
func _knock_off_mask(face: Node3D, info: DamageInfo, carried_velocity: Vector3) -> void:
	var at := face.global_transform
	face.queue_free()
	var level := get_actor().get_parent()
	var loose := _dead_mask.spawn() as RigidBody3D if _dead_mask else null
	if level == null or loose == null:
		return
	level.add_child(loose)
	# A battered mask is still battered once it is off.
	Destructible.write(loose, _dead_durability)
	# The item's mesh is the worn face at its origin, so it leaves from exactly where the
	# face was drawn.
	loose.global_transform = at
	# The body's own bones would catch it straight away; let it clear them. Only for a
	# moment: a mask that could pass through the body for good would end up underneath
	# it, where the limbs above stand between it and anyone reaching for it.
	keep_clear_of(loose, get_actor(), mask_clear_time)
	var push := get_impulse(info).normalized() if info else Vector3.ZERO
	var away := -at.basis.z
	loose.linear_velocity = carried_velocity
	loose.apply_central_impulse((push + away * 0.6 + Vector3.UP * 0.8).normalized() * mask_pop_impulse)
	loose.apply_torque_impulse(Vector3(randf_range(-1, 1), randf_range(-1, 1), randf_range(-1, 1)) * 0.02)


## Leaves the mask on a dead face and lists it with the rest of the wearer's things, so
## searching the body offers it like anything else in its pockets. Returns false when the
## wearer has no inventory, or no room in it, and the mask has to come off after all.
func _leave_mask_on() -> bool:
	var inventory := get_actor().get_node_or_null("Inventory") as Inventory
	if inventory == null or _dead_mask == null:
		return false
	_face_entry = inventory.store(_dead_mask, _dead_durability)
	if _face_entry == null:
		return false
	_face_inventory = inventory
	inventory.changed.connect(_on_face_inventory_changed)
	return true


## The face comes off as soon as its entry leaves the body's inventory — taken, dropped
## or moved into another grid.
func _on_face_inventory_changed() -> void:
	if _face_inventory.get_entries().has(_face_entry):
		return
	_face_inventory.changed.disconnect(_on_face_inventory_changed)
	_face_inventory = null
	_face_entry = null
	if _face:
		_face.queue_free()
		_face = null


## Everything of `actor` that a ray or a thrown object could run into: its own collision
## body, and every physical bone of every body it wears. An animated body keeps its
## bones in the physics world, following the pose, so an attacker's own arms and chest
## sit right in the path of its blows and throws — this is what they are kept out of.
static func colliders_of(actor: Node) -> Array[CollisionObject3D]:
	var colliders: Array[CollisionObject3D] = []
	if actor == null or not is_instance_valid(actor):
		return colliders
	if actor is CollisionObject3D:
		colliders.append(actor)
	for bone in actor.find_children("*", "PhysicalBone3D", true, false):
		colliders.append(bone)
	return colliders


## Keeps `item` from colliding with `actor` — its capsule and its limbs alike — for
## `seconds`, so something just thrown clears the hand and the body it left from
## instead of landing on its own thrower.
static func keep_clear_of(item: PhysicsBody3D, actor: Node, seconds := 0.3) -> void:
	var own_ids: Array[int] = []
	for collider in colliders_of(actor):
		item.add_collision_exception_with(collider)
		own_ids.append(collider.get_instance_id())
	# Held by id rather than captured: the item may break, or the thrower die and be
	# freed, before the timer runs.
	var item_id := item.get_instance_id()
	item.get_tree().create_timer(seconds).timeout.connect(
		func() -> void:
			var thrown := instance_from_id(item_id) as PhysicsBody3D
			if thrown == null:
				return
			for id in own_ids:
				var collider := instance_from_id(id) as Node
				if collider:
					thrown.remove_collision_exception_with(collider)
	)


## The character a collider belongs to. A fallen or flinching body's bones are colliders
## in their own right, so whatever a ray or an impact finds is passed through here to get
## back to the character that carries the Health, the Inventory and the rest. Anything
## that is not a body bone is returned as it is.
static func actor_of(node: Node) -> Node:
	if not node is PhysicalBone3D:
		return node
	var at := node.get_parent()
	while at:
		if at is NpcBody:
			return (at as NpcBody).get_actor()
		at = at.get_parent()
	return node
