class_name HumanBody
extends Node3D

## The body every human character wears — villagers, bandits, and the player once they
## fall. It is the human model on a skeleton with a physical bone for each part, and it
## owns the two ways that body answers a hit:
##
## - flinch(): everything above the hips briefly turns physical, takes the hit's impulse
##   at the part that was struck, and the pose eases back to normal. The hips stay
##   animated, so the character rocks with the blow but keeps its feet.
## - go_limp(): death. Every bone turns physical for good and the body falls wherever the
##   killing blow and its own momentum throw it.
##
## Neither is decided here. Like any death behaviour in this project, the character's
## own script calls them from its Health signals; this only knows how to do them.
##
## The scene is generated by scripts/import/build_human_body.gd. Tune the skeleton,
## shapes and joint limits there; what this script exports is tuned on the instance.

signal went_limp

## Overrides the model's material, which is how one body tells a villager from a bandit.
@export var material: Material:
	set(value):
		material = value
		if is_node_ready():
			_apply_material()
## A mask worn over the face, which is how one faction tells itself from another in the
## dark. Instanced onto the head bone when the body is ready; its origin is placed at
## `mask_offset` from the bone, facing forward (-Z).
@export var mask_scene: PackedScene
## Where the mask sits relative to the head bone, which is at the base of the skull.
@export var mask_offset := Vector3(0.0, 0.13, -0.135)
## Chance that a mask comes off and tumbles away when the body goes limp.
@export_range(0.0, 1.0) var mask_pop_chance := 0.7
## Impulse the mask leaves the face with, in newton-seconds, on top of the killing blow's
## direction.
@export var mask_pop_impulse := 0.6
## Hits in a game land harder than physics says they should: every impulse a hit puts
## into the bones is multiplied by this.
@export var impulse_scale := 2.5
## Cap on that scaled impulse, in newton-seconds, so a hurled barrel knocks a body over
## rather than launching it across the map.
@export var max_impulse := 60.0
## How far a hit shoves the whole character, as a multiple of what its impulse would do
## to a body of this mass. Read through get_knockback() by whoever moves the character.
@export var knockback_scale := 3.0

## Whether something poses this body every frame, as an NPC's BodyAnimator does. Its
## physical bones then follow the animated pose instead of staying in the rest pose.
@export var animated := false:
	set(value):
		animated = value
		if is_node_ready() and not _limp and not physical_bones.is_simulating_physics():
			_settle_physical_bones()

@export_group("Flinch")
## The bone that stays animated while the rest of the body flinches, keeping the
## character standing on it.
@export var anchor_bone := &"Hips"
## How much of the physical pose shows at the height of a flinch, 0..1.
@export_range(0.0, 1.0) var flinch_influence := 0.9
## Seconds for the pose to ease back from a flinch to the character's own.
@export var flinch_recovery := 0.55
## Damping on the bones while flinching, so a blow is absorbed rather than flailed.
@export var flinch_linear_damp := 5.0
@export var flinch_angular_damp := 7.0
## Gravity on the flinching bones. Zero, because a standing torso is an upturned
## pendulum: with gravity it would start to fold over in the time a flinch lasts.
@export var flinch_gravity_scale := 0.0

@onready var skeleton: Skeleton3D = %Skeleton
@onready var mesh: MeshInstance3D = %Mesh
@onready var physical_bones: PhysicalBoneSimulator3D = %PhysicalBones

var _bones: Array[PhysicalBone3D] = []
## Half the length of each bone's collision shape along the bone, for finding the part
## nearest a hit.
var _half_lengths := {}
## Each bone's authored gravity and damping, put back when a flinch ends.
var _authored := {}
var _limp := false
var _flinch: Tween
var _mask: Node3D


func _ready() -> void:
	for child in physical_bones.get_children():
		var bone := child as PhysicalBone3D
		if bone == null:
			continue
		_bones.append(bone)
		_half_lengths[bone] = _half_length_of(bone)
		_authored[bone] = [bone.gravity_scale, bone.linear_damp, bone.angular_damp]
	# The parts of one body never collide with each other — shoulders and chest overlap
	# at rest and would push each other apart — nor with the capsule of the character
	# wearing them.
	for i in _bones.size():
		for j in range(i + 1, _bones.size()):
			_bones[i].add_collision_exception_with(_bones[j])
	var actor := get_actor() as CollisionObject3D
	if actor and actor != self:
		physical_bones.physical_bones_add_collision_exception(actor.get_rid())
	_settle_physical_bones()
	_apply_material()
	_put_on_mask()


## The character wearing this body: the scene it was placed in, or the body itself when
## it stands alone.
func get_actor() -> Node3D:
	return owner as Node3D if owner is Node3D else self


func is_limp() -> bool:
	return _limp


## The middle of the body, wherever it has fallen: what a death camera looks at.
func get_center() -> Vector3:
	var middle := _find_bone(&"Spine")
	return middle.global_position if middle else global_position + Vector3.UP


## The vector from a bone's head to its far end — the knee to the sole, the elbow to the
## fingertips — in the body's rest frame. Read off the bone's physical body, which the
## builder centres halfway along it.
func get_bone_tail(bone_name: StringName) -> Vector3:
	var bone := _find_bone(bone_name)
	return bone.body_offset.origin * 2.0 if bone else Vector3.ZERO


## The impulse `info` puts into this body, scaled and capped.
func get_impulse(info: DamageInfo) -> Vector3:
	if info == null:
		return Vector3.ZERO
	return (info.get_impulse() * impulse_scale).limit_length(max_impulse)


## How `info` shoves the whole character: a velocity, flat along the ground, for the
## character's own movement to add and then shed.
func get_knockback(info: DamageInfo) -> Vector3:
	var impulse := get_impulse(info)
	impulse.y = 0.0
	return impulse * knockback_scale / maxf(get_total_mass(), 1.0)


func get_total_mass() -> float:
	var total := 0.0
	for bone in _bones:
		total += bone.mass
	return total


## Rocks the body with a hit that did not kill. A second hit while the first is still
## playing out adds its impulse to the motion already there.
func flinch(info: DamageInfo) -> void:
	if _limp or info == null:
		return
	var impulse := get_impulse(info)
	if impulse.is_zero_approx():
		return
	var flinching: Array[PhysicalBone3D] = []
	var names: Array[StringName] = []
	for bone in _bones:
		if bone.bone_name != String(anchor_bone):
			flinching.append(bone)
			names.append(StringName(bone.bone_name))
	if flinching.is_empty():
		return
	if not physical_bones.is_simulating_physics():
		for bone in flinching:
			bone.gravity_scale = flinch_gravity_scale
			bone.linear_damp = flinch_linear_damp
			bone.angular_damp = flinch_angular_damp
		physical_bones.influence = 0.0
		physical_bones.active = true
		physical_bones.physical_bones_start_simulation(names)
	_push(_nearest_bone(info.position, flinching), impulse, info.position)

	# Straight up to full strength, held a moment, then eased back. A hit landing
	# mid-recovery ramps up from wherever the pose is rather than snapping to it.
	if _flinch:
		_flinch.kill()
	_flinch = create_tween()
	_flinch.tween_property(physical_bones, "influence", flinch_influence, 0.05)
	_flinch.tween_property(physical_bones, "influence", 0.0, flinch_recovery).set_trans(
		Tween.TRANS_SINE
	).set_ease(Tween.EASE_IN_OUT)
	_flinch.tween_callback(_end_flinch)


## Lets the whole body fall, for good. `carried_velocity` is how the character was
## moving, so a body killed mid-run keeps going as it drops; the killing blow's impulse
## lands on top of that at the part it struck.
func go_limp(info: DamageInfo = null, carried_velocity := Vector3.ZERO) -> void:
	if _limp:
		return
	_limp = true
	if _flinch:
		_flinch.kill()
		_flinch = null
	for bone in _bones:
		_restore_authored(bone)
	physical_bones.active = true
	# Bones already flinching keep their motion; the rest start from the current pose.
	physical_bones.physical_bones_start_simulation()
	var blend := create_tween()
	blend.tween_property(physical_bones, "influence", 1.0, 0.08)
	for bone in _bones:
		bone.linear_velocity += carried_velocity
	if info:
		var impulse := get_impulse(info)
		_push(_nearest_bone(info.position, _bones), impulse, info.position)
	if _mask and randf() < mask_pop_chance:
		# Deferred: adding a body from inside a physics callback is not allowed.
		_knock_off_mask.call_deferred(_mask, info, carried_velocity)
		_mask = null
	went_limp.emit()


func _end_flinch() -> void:
	_flinch = null
	if _limp:
		return
	physical_bones.physical_bones_stop_simulation()
	_settle_physical_bones()
	for bone in _bones:
		_restore_authored(bone)


## Puts the simulator back to rest between hits. On a body that is not animated it sleeps
## and the bones stay where the rest pose put them. On an animated one it keeps running
## with no influence on the pose, which is what carries the bones along with the
## animation — so a hit lands on the limb where it is drawn, and a flinch or a fall starts
## from the pose the body was really in.
func _settle_physical_bones() -> void:
	physical_bones.influence = 0.0
	physical_bones.active = animated


func _restore_authored(bone: PhysicalBone3D) -> void:
	var authored: Array = _authored[bone]
	bone.gravity_scale = authored[0]
	bone.linear_damp = authored[1]
	bone.angular_damp = authored[2]


## Applies `impulse` to `bone` at `at`, or through its centre when the hit carried no
## position.
func _push(bone: PhysicalBone3D, impulse: Vector3, at: Vector3) -> void:
	if bone == null or impulse.is_zero_approx():
		return
	if at.is_zero_approx():
		bone.apply_central_impulse(impulse)
	else:
		# Clamped to the bone, so a point recorded at the surface of a capsule or at a
		# thrown rock's centre does not become a long lever arm.
		var offset := (at - bone.global_position).limit_length(_half_lengths[bone] + 0.1)
		bone.apply_impulse(impulse, offset)


## The bone among `candidates` whose segment passes closest to `point`, or the chest when
## the hit recorded no point.
func _nearest_bone(point: Vector3, candidates: Array[PhysicalBone3D]) -> PhysicalBone3D:
	if point.is_zero_approx():
		var chest := _find_bone(&"Chest")
		return chest if chest in candidates else candidates.front()
	var nearest: PhysicalBone3D = null
	var nearest_distance := INF
	for bone in candidates:
		var axis := bone.global_basis.y.normalized()
		var half: float = _half_lengths[bone]
		var along := clampf((point - bone.global_position).dot(axis), -half, half)
		var distance := point.distance_to(bone.global_position + axis * along)
		if distance < nearest_distance:
			nearest = bone
			nearest_distance = distance
	return nearest


func _find_bone(bone_name: StringName) -> PhysicalBone3D:
	for bone in _bones:
		if bone.bone_name == String(bone_name):
			return bone
	return null


func _half_length_of(bone: PhysicalBone3D) -> float:
	for child in bone.get_children():
		var shape := (child as CollisionShape3D).shape if child is CollisionShape3D else null
		if shape is CapsuleShape3D:
			var capsule := shape as CapsuleShape3D
			return maxf(capsule.height * 0.5 - capsule.radius, 0.0)
		if shape is BoxShape3D:
			return (shape as BoxShape3D).size.y * 0.5
	return 0.0


func _apply_material() -> void:
	if mesh:
		mesh.material_override = material


## Hangs the mask on the head bone, so it turns, flinches and falls with the head. It is
## added here rather than in the generated scene so that rebuilding the body keeps it.
func _put_on_mask() -> void:
	if mask_scene == null:
		return
	var attachment := BoneAttachment3D.new()
	attachment.name = "HeadAttachment"
	attachment.bone_name = "Head"
	skeleton.add_child(attachment)
	_mask = mask_scene.instantiate() as Node3D
	_mask.position = mask_offset
	attachment.add_child(_mask)


## The mask comes away from a falling body as a small rigid body of its own, carried off
## by the blow and the body's own momentum. It stays in the level after that.
func _knock_off_mask(mask: Node3D, info: DamageInfo, carried_velocity: Vector3) -> void:
	var level := get_actor().get_parent()
	if level == null:
		return
	var at := mask.global_transform
	var loose := RigidBody3D.new()
	loose.name = "FallenMask"
	loose.mass = 0.3
	loose.angular_damp = 1.0
	var shape := CollisionShape3D.new()
	var box := BoxShape3D.new()
	box.size = Vector3(0.22, 0.26, 0.06)
	shape.shape = box
	loose.add_child(shape)
	level.add_child(loose)
	loose.global_transform = at
	# The body's own bones would catch it straight away; let it clear them.
	for bone in _bones:
		loose.add_collision_exception_with(bone)
	mask.get_parent().remove_child(mask)
	loose.add_child(mask)
	mask.transform = Transform3D.IDENTITY
	var push := get_impulse(info).normalized() if info else Vector3.ZERO
	var away := -at.basis.z
	loose.linear_velocity = carried_velocity
	loose.apply_central_impulse((push + away * 0.6 + Vector3.UP * 0.8).normalized() * mask_pop_impulse)
	loose.apply_torque_impulse(Vector3(randf_range(-1, 1), randf_range(-1, 1), randf_range(-1, 1)) * 0.02)


## The character a collider belongs to. A fallen or flinching body's bones are colliders
## in their own right, so whatever a ray or an impact finds is passed through here to get
## back to the character that carries the Health, the Inventory and the rest. Anything
## that is not a body bone is returned as it is.
static func actor_of(node: Node) -> Node:
	if not node is PhysicalBone3D:
		return node
	var at := node.get_parent()
	while at:
		if at is HumanBody:
			return (at as HumanBody).get_actor()
		at = at.get_parent()
	return node
