extends Node3D

## The walking chair: a Windsor chair walking on four long clay limbs, with a round clay
## head hanging under the front of its seat. The head wears a mask like any human face
## does, which in this world is what gives it a side.
##
## The scene is generated by tools/import/build_walking_chair.gd; the mask is put on here
## rather than in the generated scene, so rebuilding the chair keeps it.
##
## It walks by code, not keyframes: it crawls on its hands in a diagonal gait (front left
## with back right, then front right with back left). Each limb is a two-bone IK chain
## reaching for its hand's position; a hand on the ground stays exactly where it was
## planted, and the gait advances with the distance the chair actually moves, so whatever
## moves it (a creature body, a capture script) never makes the hands slide.

## The mask worn on the front of the head. Its worn_scene is instanced on %Head, origin at
## `mask_offset` from the head's centre, facing forward (-Z). Changing it swaps the face.
@export var mask: MaskData:
	set(value):
		if value == mask:
			return
		mask = value
		if is_node_ready():
			_put_on_mask()
## Where the mask sits relative to the head's centre: just in front of the ball.
@export var mask_offset := Vector3(0.0, 0.0, -0.165)
## Ground covered by one full gait cycle (both diagonal pairs step once), metres.
@export var stride := 0.5
## How high a swinging hand lifts, metres.
@export var lift := 0.12
## Off: the limbs keep the generated reference pose (for the model sheet).
@export var animate := true

## The limbs' bones, metres (the builder's THIGH and SHIN).
const THIGH := 0.46
const SHIN := 0.62
## The diagonal pair that swings in the first half of the cycle; the others swing after.
const PAIR_A := ["FL", "BR"]
const CORNERS := ["FL", "FR", "BL", "BR"]
## Gait speed while it settles its hands after stopping, cycles per second.
const SETTLE_RATE := 1.2

var _face: Node3D
## Per corner: [hip, knee, wrist] pivots.
var _limbs := {}
## Per corner: where the hand rests, in the chair's own space.
var _home := {}
## Per corner: the hand's planted world position (the swing's start while it swings).
var _plant := {}
## Per corner: the hand's world position this frame.
var _hand := {}
## Per corner: the hand's rest orientation relative to the chair.
var _hand_basis := {}
var _phase := 0.0
var _last_pos := Vector3.ZERO
var _velocity := Vector3.ZERO
## 1 while walking, easing to 0 when it stands.
var _moving := 0.0
var _idle_time := 0.0
var _body_rest := Vector3.ZERO
## Below 0 standing; rises 0..1 as a dead chair sinks onto its splayed limbs.
var _collapse := -1.0


func _ready() -> void:
	_put_on_mask()
	_body_rest = (%Body as Node3D).position
	var inv := global_transform.affine_inverse()
	for corner in CORNERS:
		var wrist := get_node("%Wrist" + corner) as Node3D
		_limbs[corner] = [get_node("%Hip" + corner), get_node("%Knee" + corner), wrist]
		# A little in under the seat from the built pose, which is nearly at full stretch.
		_home[corner] = (inv * wrist.global_position) * Vector3(0.85, 1.0, 0.8)
		_hand_basis[corner] = global_basis.inverse() * wrist.global_basis
	# The front right arm is built reaching; standing, it mirrors the front left one.
	var fl: Vector3 = _home["FL"]
	_home["FR"] = Vector3(-fl.x, fl.y, fl.z)
	var mirror := Basis.from_scale(Vector3(-1.0, 1.0, 1.0))
	_hand_basis["FR"] = mirror * (_hand_basis["FL"] as Basis) * mirror
	for corner in CORNERS:
		_plant[corner] = global_transform * (_home[corner] as Vector3)
		_hand[corner] = _plant[corner]
	_last_pos = global_position
	var anim := get_node_or_null("%AnimationPlayer") as AnimationPlayer
	if anim:
		anim.stop()


func _process(delta: float) -> void:
	if not animate or delta <= 0.0:
		return
	if _collapse >= 0.0:
		_collapse = minf(_collapse + delta * 2.5, 1.0)
		_pose_collapsed()
		return
	var moved := global_position - _last_pos
	moved.y = 0.0
	_last_pos = global_position
	_velocity = _velocity.lerp(moved / delta, minf(1.0, delta * 8.0))
	var walking := moved.length() > 0.0005
	_moving = move_toward(_moving, 1.0 if walking else 0.0, delta * 3.0)
	if walking and not _swinging() and _stretch(_next_pair()) < _stretch(_other(_next_pair())):
		# Setting off: the pair left furthest behind steps first.
		_phase += 0.5
	var old_phase := _phase
	if walking:
		_phase += minf(moved.length() / stride, 0.45)
		_idle_time = 0.0
	elif _swinging() or _needs_settle():
		_phase += delta * SETTLE_RATE
		_idle_time = 0.0
	else:
		_idle_time += delta
	# A pair's swing ends when the phase crosses a half cycle: it lands and plants.
	if floorf(old_phase * 2.0) != floorf(_phase * 2.0):
		var landed: Array = PAIR_A if fposmod(old_phase, 1.0) < 0.5 else _pair_b()
		for corner in landed:
			_plant[corner] = _target(corner)
		if not walking:
			_phase = floorf(_phase * 2.0) / 2.0
	_place_hands()
	_pose_body()
	for corner in CORNERS:
		_solve(corner)


## The world position of `corner`'s hand while it is planted, or null while it swings or
## gestures (for checks).
func planted_hand(corner: String) -> Variant:
	if (_hand[corner] as Vector3).is_equal_approx(_plant[corner]):
		return _plant[corner]
	return null


## Dead: the limbs give way and splay out, the seat drops onto them, and the mask pops off
## the head as a loose item in `level`, the way a fallen villager's does. Returns the
## dropped mask, or null.
func collapse(level: Node) -> Node3D:
	if _collapse >= 0.0:
		return null
	_collapse = 0.0
	for corner in CORNERS:
		_plant[corner] = _hand[corner]
	return _drop_mask(level)


func is_collapsed() -> bool:
	return _collapse >= 0.0


func _drop_mask(level: Node) -> Node3D:
	if _face == null or mask == null or level == null:
		return null
	var at := _face.global_transform
	_face.queue_free()
	_face = null
	var loose := mask.spawn()
	if loose == null:
		return null
	level.add_child(loose)
	loose.global_transform = at
	if loose is RigidBody3D:
		var away := -at.basis.z
		(loose as RigidBody3D).apply_central_impulse((away * 0.6 + Vector3.UP * 0.8).normalized() * 1.2)
	return loose


func _pose_collapsed() -> void:
	var c := smoothstep(0.0, 1.0, _collapse)
	for corner in CORNERS:
		var home: Vector3 = _home[corner]
		var splayed: Vector3 = global_transform * Vector3(home.x * 2.2, home.y, home.z * 1.8)
		_hand[corner] = (_plant[corner] as Vector3).lerp(splayed, c)
	var body := %Body as Node3D
	body.position = _body_rest.lerp(Vector3(0.0, 0.35, 0.0), c)
	body.rotation = Vector3(0.2 * c, 0.0, 0.25 * c)
	(%Head as Node3D).rotation = Vector3(0.6 * c, 0.0, 0.4 * c)
	for corner in CORNERS:
		_solve(corner)


func _put_on_mask() -> void:
	if _face:
		_face.queue_free()
		_face = null
	if mask == null or mask.worn_scene == null:
		return
	_face = mask.worn_scene.instantiate() as Node3D
	_face.position = mask_offset
	%Head.add_child(_face)


## True while one pair is mid-swing.
func _swinging() -> bool:
	var f := fposmod(_phase * 2.0, 1.0)
	return f > 0.001


func _needs_settle() -> bool:
	for corner in CORNERS:
		if (_plant[corner] as Vector3).distance_to(_target(corner)) > stride * 0.15:
			return true
	return false


func _pair_b() -> Array:
	return _other(PAIR_A)


func _other(pair: Array) -> Array:
	return CORNERS.filter(func(c: String) -> bool: return not c in pair)


## The pair that swings next from a standstill.
func _next_pair() -> Array:
	return PAIR_A if fposmod(_phase, 1.0) < 0.5 else _pair_b()


## How far the pair's most stretched limb reaches from its hip to its planted hand.
func _stretch(pair: Array) -> float:
	var most := 0.0
	for corner in pair:
		var hip := (_limbs[corner] as Array)[0] as Node3D
		most = maxf(most, hip.global_position.distance_to(_plant[corner]))
	return most


## Where `corner`'s hand lands: its home, pushed ahead along the motion by a quarter stride
## so the planted hand passes under its shoulder halfway through carrying the weight.
func _target(corner: String) -> Vector3:
	var home: Vector3 = _home[corner]
	var t: Vector3 = global_transform * home
	if _velocity.length() > 0.05 and _moving > 0.5:
		t += _velocity.normalized() * stride * 0.25
	t.y = global_position.y + home.y
	return t


func _place_hands() -> void:
	var swinging_a := fposmod(_phase, 1.0) < 0.5
	var swing := fposmod(_phase * 2.0, 1.0)
	for corner in CORNERS:
		if not _swinging() or (corner in PAIR_A) != swinging_a:
			_hand[corner] = _plant[corner]
			continue
		var p: Vector3 = (_plant[corner] as Vector3).lerp(_target(corner), smoothstep(0.0, 1.0, swing))
		p.y += sin(swing * PI) * lift
		_hand[corner] = p
	_idle_gestures()


## Standing still: the front left fingers tap now and then, and every so often the front
## right arm reaches out in front of it.
func _idle_gestures() -> void:
	var still := 1.0 - _moving
	if still <= 0.0 or _idle_time <= 0.0:
		return
	var beat := fposmod(_idle_time, 5.0)
	var tap := maxf(0.0, sin(_idle_time * 9.0)) * 0.05
	tap *= smoothstep(1.0, 1.5, beat) * (1.0 - smoothstep(3.5, 4.0, beat))
	_hand["FL"] = (_hand["FL"] as Vector3) + Vector3.UP * tap * still
	var cycle := fposmod(_idle_time, 11.0)
	var reach := smoothstep(6.0, 6.8, cycle) * (1.0 - smoothstep(8.6, 9.4, cycle)) * still
	if reach > 0.0:
		var out: Vector3 = global_transform * Vector3(0.3, 0.8, -0.8)
		_hand["FR"] = (_hand["FR"] as Vector3).lerp(out, reach)


## A light bob twice per cycle (once per step), a sway side to side, and the head lolling
## along; standing still the head tilts, curious.
func _pose_body() -> void:
	var cycle := _phase * TAU
	var body := %Body as Node3D
	# The built pose stands on nearly straight limbs; it crouches a little to walk, so
	# the reach a stride needs is left in them.
	var crouch := -0.05 - 0.16 * _moving
	body.position = _body_rest + Vector3(0.0, crouch + 0.03 * cos(cycle * 2.0) * _moving, 0.0)
	body.rotation = Vector3(0.0, 0.0, 0.05 * sin(cycle) * _moving)
	var tilt := 0.25 * sin(_idle_time * 0.8) * (1.0 - _moving)
	(%Head as Node3D).rotation = Vector3(0.0, 0.0, tilt - 0.12 * sin(cycle) * _moving)


## Two-bone IK: turn the hip and knee so the wrist reaches the hand's position, the knee
## bending outwards and up like a spider's, and keep the hand on the chair's heading.
func _solve(corner: String) -> void:
	var bones: Array = _limbs[corner]
	var hip: Node3D = bones[0]
	var p := hip.global_position
	var to: Vector3 = (_hand[corner] as Vector3) - p
	var d := clampf(to.length(), absf(THIGH - SHIN) + 0.01, THIGH + SHIN - 0.001)
	var dir := to.normalized()
	var pole := (global_basis.x * signf(hip.position.x) + global_basis.y * 0.6).normalized()
	var perp := (pole - dir * pole.dot(dir)).normalized()
	var axis := dir.cross(perp).normalized()
	var cos_a := clampf((THIGH * THIGH + d * d - SHIN * SHIN) / (2.0 * THIGH * d), -1.0, 1.0)
	var k := p + (dir * cos_a + perp * sqrt(1.0 - cos_a * cos_a)) * THIGH
	var w := p + dir * d
	hip.global_basis = _bone_basis(axis, (p - k).normalized())
	(bones[1] as Node3D).global_basis = _bone_basis(axis, (k - w).normalized())
	(bones[2] as Node3D).global_basis = global_basis * (_hand_basis[corner] as Basis)


## A bone's basis: its -Y runs down the bone, X is the joint's hinge axis.
func _bone_basis(axis: Vector3, y: Vector3) -> Basis:
	var z := axis.cross(y).normalized()
	return Basis(y.cross(z).normalized(), y, z)
