extends Node3D

## The walking chair: a Windsor chair walking on four long clay limbs, with a round clay
## head hanging under the front of its seat. The head wears a mask like any human face
## does, which in this world is what gives it a side.
##
## The scene is generated by tools/import/build_walking_chair.gd; the mask is put on here
## rather than in the generated scene, so rebuilding the chair keeps it.

## The mask worn on the front of the head. Its worn_scene is instanced on %Head, origin at
## `mask_offset` from the head's centre, facing forward (-Z). Changing it swaps the face.
@export var mask: MaskData:
	set(value):
		if value == mask:
			return
		mask = value
		if is_node_ready():
			_put_on_mask()
## Where the mask sits relative to the head's centre: just in front of the ball.
@export var mask_offset := Vector3(0.0, 0.0, -0.165)

var _face: Node3D


func _ready() -> void:
	_put_on_mask()


func _put_on_mask() -> void:
	if _face:
		_face.queue_free()
		_face = null
	if mask == null or mask.worn_scene == null:
		return
	_face = mask.worn_scene.instantiate() as Node3D
	_face.position = mask_offset
	%Head.add_child(_face)
