extends Node3D

## The walking chair: a Windsor chair walking on four long clay limbs, with a round clay
## head hanging under the front of its seat. The head wears a mask like any human face
## does, which in this world is what gives it a side.
##
## The scene is generated by tools/import/build_walking_chair.gd; the mask is put on here
## rather than in the generated scene, so rebuilding the chair keeps it.
##
## It walks by code, not keyframes: it crawls on its hands in a four-beat gait, one limb
## after another (back left, front left, back right, front right), each a little off the
## beat and no two steps quite the same, so three hands nearly always hold the ground.
## Each limb is a two-bone IK chain
## reaching for its hand's position; a hand on the ground stays exactly where it was
## planted, and the gait advances with the distance the chair actually moves, so whatever
## moves it (a creature body, a capture script) never makes the hands slide.

## The mask worn on the front of the head. Its worn_scene is instanced on %Head, origin at
## `mask_offset` from the head's centre, facing forward (-Z). Changing it swaps the face.
@export var mask: MaskData:
	set(value):
		if value == mask:
			return
		mask = value
		if is_node_ready():
			_put_on_mask()
## Where the mask sits relative to the head's centre: just in front of the ball.
@export var mask_offset := Vector3(0.0, 0.0, -0.165)
## Ground covered by one full gait cycle (every limb steps once), metres.
@export var stride := 0.6
## How high a swinging hand lifts, metres.
@export var lift := 0.12
## Off: the limbs keep the generated reference pose (for the model sheet).
@export var animate := true

## The limbs' bones, metres (the builder's THIGH and SHIN).
const THIGH := 0.46
const SHIN := 0.62
const CORNERS := ["FL", "FR", "BL", "BR"]
## Where in the cycle each limb lifts: a crawling creature's lateral sequence.
const BEAT := {"BL": 0.0, "FL": 0.25, "BR": 0.5, "FR": 0.75}
## How much of a cycle one step takes at walking pace, and at a run, where a limb lifts
## just before the one ahead of it has landed.
const SWING_WALK := 0.2
const SWING_RUN := 0.32
## Ground speed (metres a second) above which it counts as running: two limbs may then
## be in the air at once; walking, a limb waits for the one in the air to land.
const RUN_SPEED := 1.2
## How far off the beat a step may lift (cycles), and how uneven step lengths are.
const BEAT_JITTER := 0.025
const STEP_JITTER := 0.15
## Gait speed while it settles its hands after stopping, cycles per second.
const SETTLE_RATE := 1.6

var _face: Node3D
## Per corner: [hip, knee, wrist] pivots.
var _limbs := {}
## Per corner: where the hand rests, in the chair's own space.
var _home := {}
## Per corner: the hand's planted world position (the swing's start while it swings).
var _plant := {}
## Per corner: the hand's world position this frame.
var _hand := {}
## Per corner: the hand's rest orientation relative to the chair.
var _hand_basis := {}
var _phase := 0.0
## Per corner: the phase at which it next lifts, and the beat that is jittered from.
var _next_lift := {}
var _on_beat := {}
## Per corner: progress of its step 0..1, or -1 while planted.
var _swing := {}
## Per corner: the share of a cycle its current step lasts.
var _swing_len := {}
## Per corner: this step's length and height factors (uneven, step to step).
var _step_scale := {}
var _lift_scale := {}
## True once it has set off; false again when it has stopped and settled.
var _under_way := false
var _rng := RandomNumberGenerator.new()
var _last_pos := Vector3.ZERO
var _velocity := Vector3.ZERO
## 1 while walking, easing to 0 when it stands.
var _moving := 0.0
var _idle_time := 0.0
var _body_rest := Vector3.ZERO
## Below 0 standing; rises 0..1 as a dead chair sinks onto its splayed limbs.
var _collapse := -1.0


func _ready() -> void:
	_put_on_mask()
	_body_rest = (%Body as Node3D).position
	var inv := global_transform.affine_inverse()
	for corner in CORNERS:
		var wrist := get_node("%Wrist" + corner) as Node3D
		_limbs[corner] = [get_node("%Hip" + corner), get_node("%Knee" + corner), wrist]
		# A little in under the seat from the built pose, which is nearly at full stretch.
		_home[corner] = (inv * wrist.global_position) * Vector3(0.85, 1.0, 0.8)
		_hand_basis[corner] = global_basis.inverse() * wrist.global_basis
	# The front right arm is built reaching; standing, it mirrors the front left one.
	var fl: Vector3 = _home["FL"]
	_home["FR"] = Vector3(-fl.x, fl.y, fl.z)
	var mirror := Basis.from_scale(Vector3(-1.0, 1.0, 1.0))
	_hand_basis["FR"] = mirror * (_hand_basis["FL"] as Basis) * mirror
	_rng.randomize()
	for corner in CORNERS:
		_plant[corner] = global_transform * (_home[corner] as Vector3)
		_hand[corner] = _plant[corner]
		_swing[corner] = -1.0
		_swing_len[corner] = SWING_WALK
		_step_scale[corner] = 1.0
		_lift_scale[corner] = 1.0
		_on_beat[corner] = BEAT[corner]
		_next_lift[corner] = BEAT[corner]
	_last_pos = global_position
	var anim := get_node_or_null("%AnimationPlayer") as AnimationPlayer
	if anim:
		anim.stop()


func _process(delta: float) -> void:
	if not animate or delta <= 0.0:
		return
	if _collapse >= 0.0:
		_collapse = minf(_collapse + delta * 2.5, 1.0)
		_pose_collapsed()
		return
	var moved := global_position - _last_pos
	moved.y = 0.0
	_last_pos = global_position
	_velocity = _velocity.lerp(moved / delta, minf(1.0, delta * 8.0))
	var walking := moved.length() > 0.0005
	_moving = move_toward(_moving, 1.0 if walking else 0.0, delta * 3.0)
	if walking and not _under_way and _airborne() == 0:
		_set_off()
	var advance := 0.0
	if walking:
		advance = minf(moved.length() / stride, 0.3)
		_idle_time = 0.0
	elif _airborne() > 0 or _needs_settle():
		# Stopping: the step in the air finishes, then any hand left out of place steps in.
		advance = delta * SETTLE_RATE
		_idle_time = 0.0
	else:
		_under_way = false
		_idle_time += delta
	_phase += advance
	_step(advance, walking)
	_place_hands()
	_pose_body()
	for corner in CORNERS:
		_solve(corner)


## The world position of `corner`'s hand while it is planted, or null while it swings or
## gestures (for checks).
func planted_hand(corner: String) -> Variant:
	if (_hand[corner] as Vector3).is_equal_approx(_plant[corner]):
		return _plant[corner]
	return null


## Dead: the limbs give way and splay out, the seat drops onto them, and the mask pops off
## the head as a loose item in `level`, the way a fallen villager's does. Returns the
## dropped mask, or null.
func collapse(level: Node) -> Node3D:
	if _collapse >= 0.0:
		return null
	_collapse = 0.0
	for corner in CORNERS:
		_plant[corner] = _hand[corner]
	return _drop_mask(level)


func is_collapsed() -> bool:
	return _collapse >= 0.0


func _drop_mask(level: Node) -> Node3D:
	if _face == null or mask == null or level == null:
		return null
	var at := _face.global_transform
	_face.queue_free()
	_face = null
	var loose := mask.spawn()
	if loose == null:
		return null
	level.add_child(loose)
	loose.global_transform = at
	if loose is RigidBody3D:
		var away := -at.basis.z
		(loose as RigidBody3D).apply_central_impulse((away * 0.6 + Vector3.UP * 0.8).normalized() * 1.2)
	return loose


func _pose_collapsed() -> void:
	var c := smoothstep(0.0, 1.0, _collapse)
	for corner in CORNERS:
		var home: Vector3 = _home[corner]
		var splayed: Vector3 = global_transform * Vector3(home.x * 2.2, home.y, home.z * 1.8)
		_hand[corner] = (_plant[corner] as Vector3).lerp(splayed, c)
	var body := %Body as Node3D
	body.position = _body_rest.lerp(Vector3(0.0, 0.35, 0.0), c)
	body.rotation = Vector3(0.2 * c, 0.0, 0.25 * c)
	(%Head as Node3D).rotation = Vector3(0.6 * c, 0.0, 0.4 * c)
	for corner in CORNERS:
		_solve(corner)


func _put_on_mask() -> void:
	if _face:
		_face.queue_free()
		_face = null
	if mask == null or mask.worn_scene == null:
		return
	_face = mask.worn_scene.instantiate() as Node3D
	_face.position = mask_offset
	%Head.add_child(_face)


## How many hands are in the air.
func _airborne() -> int:
	var count := 0
	for corner in CORNERS:
		if _swing[corner] >= 0.0:
			count += 1
	return count


func _needs_settle() -> bool:
	for corner in CORNERS:
		if _out_of_place(corner):
			return true
	return false


func _out_of_place(corner: String) -> bool:
	return (_plant[corner] as Vector3).distance_to(_target(corner)) > stride * 0.15


## Setting off from a standstill: the hand left furthest behind steps first, and the
## others follow it in the gait's order.
func _set_off() -> void:
	var dir := _velocity.normalized()
	var first: String = CORNERS[0]
	var behind := INF
	for corner in CORNERS:
		var home: Vector3 = global_transform * (_home[corner] as Vector3)
		# Rear limbs win a tie: their hands are behind the body to begin with.
		var lag := ((_plant[corner] as Vector3) - home).dot(dir) + (home - global_position).dot(dir) * 0.1
		if lag < behind:
			behind = lag
			first = corner
	for corner in CORNERS:
		_on_beat[corner] = _phase + fposmod(BEAT[corner] - BEAT[first], 1.0)
		_next_lift[corner] = _on_beat[corner]
		if corner != first:
			_next_lift[corner] += _rng.randf_range(-BEAT_JITTER, BEAT_JITTER)
	_under_way = true


## Advance the steps by `advance` cycles: hands in the air move on and land when their
## step is done; a hand whose beat has come lifts, unless too many are up already.
func _step(advance: float, walking: bool) -> void:
	for corner in CORNERS:
		if _swing[corner] < 0.0:
			continue
		_swing[corner] += advance / (_swing_len[corner] as float)
		if _swing[corner] >= 1.0:
			_swing[corner] = -1.0
			_plant[corner] = _target(corner)
	var speed := _velocity.length() if walking else 0.0
	var most_up := 2 if speed > RUN_SPEED else 1
	var order := CORNERS.duplicate()
	order.sort_custom(func(a: String, b: String) -> bool: return _next_lift[a] < _next_lift[b])
	for corner in order:
		if _swing[corner] >= 0.0 or _phase < _next_lift[corner]:
			continue
		if not walking and not _out_of_place(corner):
			# Stopping: a hand already in place keeps still and lets its beat go by.
			_on_beat[corner] += 1.0
			_next_lift[corner] += 1.0
			continue
		if _airborne() >= most_up:
			# Waits for the hand in the air to land.
			break
		_swing[corner] = 0.0
		_swing_len[corner] = lerpf(SWING_WALK, SWING_RUN, clampf((speed - 0.8) / 0.8, 0.0, 1.0))
		_step_scale[corner] = 1.0 + _rng.randf_range(-STEP_JITTER, STEP_JITTER)
		_lift_scale[corner] = _rng.randf_range(0.75, 1.3)
		_on_beat[corner] += 1.0
		_next_lift[corner] = maxf(_on_beat[corner], _phase + 0.5) + _rng.randf_range(-BEAT_JITTER, BEAT_JITTER)


## Where `corner`'s hand lands: its home, pushed ahead along the motion (by a step that is
## a little longer or shorter each time) so the planted hand passes under its shoulder
## about halfway through carrying the weight.
func _target(corner: String) -> Vector3:
	var home: Vector3 = _home[corner]
	var t: Vector3 = global_transform * home
	if _velocity.length() > 0.05 and _moving > 0.5:
		t += _velocity.normalized() * stride * 0.35 * (_step_scale[corner] as float)
	t.y = global_position.y + home.y
	return t


func _place_hands() -> void:
	for corner in CORNERS:
		var u: float = _swing[corner]
		if u < 0.0:
			_hand[corner] = _plant[corner]
			continue
		var p: Vector3 = (_plant[corner] as Vector3).lerp(_target(corner), smoothstep(0.0, 1.0, u))
		p.y += sin(u * PI) * lift * (_lift_scale[corner] as float)
		_hand[corner] = p
	_idle_gestures()


## Standing still: the front left fingers tap now and then, and every so often the front
## right arm reaches out in front of it.
func _idle_gestures() -> void:
	var still := 1.0 - _moving
	if still <= 0.0 or _idle_time <= 0.0:
		return
	var beat := fposmod(_idle_time, 5.0)
	var tap := maxf(0.0, sin(_idle_time * 9.0)) * 0.05
	tap *= smoothstep(1.0, 1.5, beat) * (1.0 - smoothstep(3.5, 4.0, beat))
	_hand["FL"] = (_hand["FL"] as Vector3) + Vector3.UP * tap * still
	var cycle := fposmod(_idle_time, 11.0)
	var reach := smoothstep(6.0, 6.8, cycle) * (1.0 - smoothstep(8.6, 9.4, cycle)) * still
	if reach > 0.0:
		var out: Vector3 = global_transform * Vector3(0.3, 0.8, -0.8)
		_hand["FR"] = (_hand["FR"] as Vector3).lerp(out, reach)


## The body shifts its weight off each hand in the air, dipping and leaning away from it,
## and the head lolls along; standing still the head tilts, curious.
func _pose_body() -> void:
	var cycle := _phase * TAU
	var body := %Body as Node3D
	# The built pose stands on nearly straight limbs; it crouches a little to walk, so
	# the reach a stride needs is left in them.
	var crouch := -0.05 - 0.16 * _moving
	var shift := Vector3(0.0, crouch, 0.0)
	var lean := Vector3.ZERO
	for corner in CORNERS:
		var u: float = _swing[corner]
		if u < 0.0:
			continue
		var w := sin(u * PI)
		var home: Vector3 = _home[corner]
		var side := signf(home.x)
		var end := signf(home.z)
		shift += Vector3(-side * 0.035, -0.02, -end * 0.025) * w
		# The lifted corner rises a touch: +Z roll lifts the +X side, +X pitch the front.
		lean += Vector3(-end * 0.035, 0.0, side * 0.05) * w
	body.position = _body_rest + shift
	body.rotation = lean
	var tilt := 0.25 * sin(_idle_time * 0.8) * (1.0 - _moving)
	(%Head as Node3D).rotation = Vector3(0.0, 0.0, tilt - 0.12 * sin(cycle) * _moving)


## Two-bone IK: turn the hip and knee so the wrist reaches the hand's position, the knee
## bending outwards and up like a spider's, and keep the hand on the chair's heading.
func _solve(corner: String) -> void:
	var bones: Array = _limbs[corner]
	var hip: Node3D = bones[0]
	var p := hip.global_position
	var to: Vector3 = (_hand[corner] as Vector3) - p
	var d := clampf(to.length(), absf(THIGH - SHIN) + 0.01, THIGH + SHIN - 0.001)
	var dir := to.normalized()
	var pole := (global_basis.x * signf(hip.position.x) + global_basis.y * 0.6).normalized()
	var perp := (pole - dir * pole.dot(dir)).normalized()
	var axis := dir.cross(perp).normalized()
	var cos_a := clampf((THIGH * THIGH + d * d - SHIN * SHIN) / (2.0 * THIGH * d), -1.0, 1.0)
	var k := p + (dir * cos_a + perp * sqrt(1.0 - cos_a * cos_a)) * THIGH
	var w := p + dir * d
	hip.global_basis = _bone_basis(axis, (p - k).normalized())
	(bones[1] as Node3D).global_basis = _bone_basis(axis, (k - w).normalized())
	(bones[2] as Node3D).global_basis = global_basis * (_hand_basis[corner] as Basis)


## A bone's basis: its -Y runs down the bone, X is the joint's hinge axis.
func _bone_basis(axis: Vector3, y: Vector3) -> Basis:
	var z := axis.cross(y).normalized()
	return Basis(y.cross(z).normalized(), y, z)
